// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:2741efc7-936f-4efe-a717-aa6ab7680d2f';
var aws_cognito_region = 'us-east-1';
var aws_mobile_analytics_app_id = '7530650d80eb4d5ab8f4f543bce0a94f';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = 'ffac13d9-7693-41e0-b41b-68642caec30e';
var aws_project_name = 'simple-odyssey-test';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'simpleodysseytest-mobilehub-1330207775';
var aws_sign_in_enabled = 'enable';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-east-1_L13guTaTs';
var aws_user_pools_mfa_type = 'OFF';
var aws_user_pools_web_client_id = '25ts5ffcb9qc4vn1ktoo65jfas';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
