// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:2741efc7-936f-4efe-a717-aa6ab7680d2f',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '7530650d80eb4d5ab8f4f543bce0a94f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'ffac13d9-7693-41e0-b41b-68642caec30e',
    'aws_project_name': 'simple-odyssey-test',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'simpleodysseytest-mobilehub-1330207775',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_L13guTaTs',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '25ts5ffcb9qc4vn1ktoo65jfas',
}

export default awsmobile;
